alpaca:
  api_key: ${ALPACA_API_KEY}
  base_url: https://paper-api.alpaca.markets
  enabled: false
  secret_key: ${ALPACA_SECRET_KEY}
alpha_vantage:
  api_key: ${AV_API_KEY}
  enabled: false
credential_store: environment
encrypted: false
interactive_brokers:
  account_id: ${IB_ACCOUNT_ID}
  api_key: ${IB_API_KEY}
  enabled: false
  host: localhost
  port: 7497
  secret_key: ${IB_SECRET_KEY}
