daily_limits:
  max_daily_loss_pct: 0.05
  max_drawdown_pct: 0.1
  max_trades_per_day: 50
portfolio_limits:
  max_equity_at_risk: 0.1
  max_leverage: 1.0
  min_cash_pct: 0.05
position_sizing:
  max_concentration_pct: 0.1774
  max_positions: 20
  max_sector_concentration: 0.3
  per_trade_pct: 0.05
symbol_restrictions:
  blacklist:
  - SPY
  - QQQ
  min_daily_volume_usd: 500000
  min_price: 1.0
  whitelist: []
